replicaCount: 1
image:
  repository: devbytom/pk-server
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
resources: 
  limits:
    cpu: 400m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi
ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - minikube
