replicaCount: 1
image:
  repository: docker.io/devbytom/dsock-worker
  tag: latest # this should be the commit SHA of a wishful release
  pullPolicy: IfNotPresent
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
service:
  type: ClusterIP
  port: 80
resources: 
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
env:
  PORT: 80
  DSOCK_REDIS_HOST: redis-prd.prd:6379
  DSOCK_LOG_REQUESTS: "true"
  DSOCK_DEBUG: "true"
