replicaCount: 1
image:
  repository: devbytom/pk-server
  tag: latest
  pullPolicy: Always
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
service:
  type: ClusterIP
  port: 3000
resources: 
  limits:
    cpu: 400m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi
ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - minikube
envFromSecret: server-prd-env
env:
  PORT: "3000"
  DSOCK_WORKER_URL: "dsock-worker-prd.prd"
