replicaCount: 1
image:
  repository: devbytom/pg
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5432
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
env:
  - name: POSTGRES_PASSWORD 
    value: dev
  - name: DATABASE_NAME 
    value: dev
