replicaCount: 1
image:
  repository: redis
  tag: alpine
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 6379
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
